spring.application.name=book-my-shows
spring.datasource.url=jdbc:postgresql://localhost:5432/Book-My-Shows
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update

